import 'package:hive_flutter/hive_flutter.dart';
import '../core/constants/app_constants.dart';
import '../core/utils/duration_adapter.dart';
import '../models/user.dart';
import '../models/project.dart';
import '../models/time_entry.dart';
import '../models/report.dart';
import 'logger_service.dart';

class StorageService {
  static final StorageService _instance = StorageService._internal();
  factory StorageService() => _instance;

  final _logger = LoggerService();

  late Box<User> _userBox;
  late Box<Project> _projectBox;
  late Box<TimeEntry> _timeEntryBox;
  late Box<Report> _reportBox;

  StorageService._internal();

  // Initialize Hive and open boxes
  Future<void> initialize() async {
    try {
      _logger.info('Initializing Hive storage...');

      await Hive.initFlutter();

      // Register custom adapters
      Hive.registerAdapter(DurationAdapter());

      // Register adapters (generated by build_runner)
      Hive.registerAdapter(UserAdapter());
      Hive.registerAdapter(ProjectAdapter());
      Hive.registerAdapter(TimeEntryAdapter());
      Hive.registerAdapter(ReportAdapter());

      // Open boxes
      _userBox = await Hive.openBox<User>(AppConstants.hiveBoxUser);
      _projectBox = await Hive.openBox<Project>(AppConstants.hiveBoxProjects);
      _timeEntryBox = await Hive.openBox<TimeEntry>(AppConstants.hiveBoxTimeEntries);
      _reportBox = await Hive.openBox<Report>(AppConstants.hiveBoxReports);

      _logger.info('Hive storage initialized successfully');
    } catch (e, stackTrace) {
      _logger.error('Failed to initialize storage', e, stackTrace);
      rethrow;
    }
  }

  // User operations
  Future<void> saveUser(User user) async {
    try {
      await _userBox.put('current_user', user);
      _logger.info('User saved: ${user.email}');
    } catch (e, stackTrace) {
      _logger.error('Failed to save user', e, stackTrace);
      rethrow;
    }
  }

  User? getCurrentUser() {
    try {
      return _userBox.get('current_user');
    } catch (e, stackTrace) {
      _logger.error('Failed to get current user', e, stackTrace);
      return null;
    }
  }

  Future<void> clearUser() async {
    try {
      await _userBox.delete('current_user');
      _logger.info('User cleared');
    } catch (e, stackTrace) {
      _logger.error('Failed to clear user', e, stackTrace);
      rethrow;
    }
  }

  // Project operations
  Future<void> saveProject(Project project) async {
    try {
      await _projectBox.put(project.id, project);
      _logger.debug('Project saved: ${project.name}');
    } catch (e, stackTrace) {
      _logger.error('Failed to save project', e, stackTrace);
      rethrow;
    }
  }

  Future<void> saveProjects(List<Project> projects) async {
    try {
      for (final project in projects) {
        await _projectBox.put(project.id, project);
      }
      _logger.info('Saved ${projects.length} projects');
    } catch (e, stackTrace) {
      _logger.error('Failed to save projects', e, stackTrace);
      rethrow;
    }
  }

  List<Project> getAllProjects() {
    try {
      return _projectBox.values.toList();
    } catch (e, stackTrace) {
      _logger.error('Failed to get projects', e, stackTrace);
      return [];
    }
  }

  Project? getProject(String id) {
    try {
      return _projectBox.get(id);
    } catch (e, stackTrace) {
      _logger.error('Failed to get project', e, stackTrace);
      return null;
    }
  }

  Future<void> deleteProject(String id) async {
    try {
      await _projectBox.delete(id);
      _logger.info('Project deleted: $id');
    } catch (e, stackTrace) {
      _logger.error('Failed to delete project', e, stackTrace);
      rethrow;
    }
  }

  // Time entry operations
  Future<void> saveTimeEntry(TimeEntry entry) async {
    try {
      await _timeEntryBox.put(entry.id, entry);
      _logger.debug('Time entry saved: ${entry.id}');
    } catch (e, stackTrace) {
      _logger.error('Failed to save time entry', e, stackTrace);
      rethrow;
    }
  }

  List<TimeEntry> getAllTimeEntries() {
    try {
      return _timeEntryBox.values.toList();
    } catch (e, stackTrace) {
      _logger.error('Failed to get time entries', e, stackTrace);
      return [];
    }
  }

  List<TimeEntry> getTimeEntriesByProject(String projectId) {
    try {
      return _timeEntryBox.values
          .where((entry) => entry.projectId == projectId)
          .toList();
    } catch (e, stackTrace) {
      _logger.error('Failed to get time entries for project', e, stackTrace);
      return [];
    }
  }

  TimeEntry? getRunningTimeEntry() {
    try {
      return _timeEntryBox.values.firstWhere(
        (entry) => entry.isRunning,
        orElse: () => throw Exception('No running entry'),
      );
    } catch (e) {
      return null;
    }
  }

  Future<void> deleteTimeEntry(String id) async {
    try {
      await _timeEntryBox.delete(id);
      _logger.info('Time entry deleted: $id');
    } catch (e, stackTrace) {
      _logger.error('Failed to delete time entry', e, stackTrace);
      rethrow;
    }
  }

  // Report operations
  Future<void> saveReport(Report report) async {
    try {
      await _reportBox.put(report.id, report);
      _logger.info('Report saved: ${report.id}');
    } catch (e, stackTrace) {
      _logger.error('Failed to save report', e, stackTrace);
      rethrow;
    }
  }

  List<Report> getAllReports() {
    try {
      return _reportBox.values.toList();
    } catch (e, stackTrace) {
      _logger.error('Failed to get reports', e, stackTrace);
      return [];
    }
  }

  Report? getReport(String id) {
    try {
      return _reportBox.get(id);
    } catch (e, stackTrace) {
      _logger.error('Failed to get report', e, stackTrace);
      return null;
    }
  }

  Future<void> deleteReport(String id) async {
    try {
      await _reportBox.delete(id);
      _logger.info('Report deleted: $id');
    } catch (e, stackTrace) {
      _logger.error('Failed to delete report', e, stackTrace);
      rethrow;
    }
  }

  // Clear all data
  Future<void> clearAll() async {
    try {
      await _userBox.clear();
      await _projectBox.clear();
      await _timeEntryBox.clear();
      await _reportBox.clear();
      _logger.warning('All storage cleared');
    } catch (e, stackTrace) {
      _logger.error('Failed to clear storage', e, stackTrace);
      rethrow;
    }
  }

  // Close all boxes (call on app disposal)
  Future<void> close() async {
    try {
      await _userBox.close();
      await _projectBox.close();
      await _timeEntryBox.close();
      await _reportBox.close();
      _logger.info('Storage closed');
    } catch (e, stackTrace) {
      _logger.error('Failed to close storage', e, stackTrace);
    }
  }
}
